### PR TITLE
When you create a new practice session the steps are

### PR DESCRIPTION
**Pull request by diegopego**
1) choose a problem, click [next]
2) choose a language and test-framework, click [next]
3) click [confirm]
4) click [enter the exercise]
This is too many clicks.
So
- Got rid of 3) and 4)
- The [next] button for 2) can become [ok]
- Clicking [ok] takes you straight to the kata/edit/ID URL
- In a new tab/window
- Without having to make an additional 'confirmation' click

The redirection the the exercise must done be through HREF to avoid popup block.
After a redirection, the originating window must be redirected to home. This prevents the user from inadvertently opening the same exercise.

The kata must appear on a new window/tab, so the the user cannot click on the back button. Exercise progress could be lost.

Added redirection after creating a group exercise and confirming on the avatar page.
Added redirection after joining group exercise using existing avatar.
Added redirection after entering an existing single exercise. The ID of existing exercise can be fed by GET parameters or by filling the ID text input.
Added redirection fot custom problems (single and group).

### CODE REVIEW

**Comment by JonJagger** [comment]
Hi Diego,

awesome. Before merging this it occurs to me
that when someone starts an individual session they 
are no longer shown their six character ID (with phonetics).
We need that really. So I propose that the jQuery dialog
that appears in web's /kata/edit/ID (when you start) shows
you your individual ID (and its phonetics).
Does that sound reasonable?

Also, a bit of jQuery fu...

$reenterButton.attr('href', `/kata/edit/${kataId}`);
$reenterButton.attr('target', "_blank");
$reenterButton[0].click();

I think this would normally be written:

$reenterButton
  .attr('href', `/kata/edit/${kataId}`)
  .attr('target', "_blank")
  .click();

Note the dot chaining, and that there is no need for [0]

Cheers
Jon

**Comment by diegopego** [comment]
You mean something like this?
If yes, note that I proposed changing the "cyber-dojo has built-in version control..." position. This grouping makes more sense to me.
dojo

About the jQuery, thanks!
Before submitting this PR, I tried:
```
$reenterButton.click()
$reenterButton.trigger('click');
```
This would trigger event's which are attached to an element.

To call the underlying html-element, not the jQuery-object, the cleanest way of doing is this:
`$reenterButton.[0].click()`

**Comment by diegopego** [comment]
What do you think of this? I extracted to make the intent more clear.
```
    const $editKata = (kataId) => {
      const $reenterButton = $('a.button.reenter');
      $reenterButton.attr('href', `/kata/edit/${kataId}`).attr('target', "_blank");
      $reenterButton[0].click();
    }
    $div.click(() => {
        $editKata(kataId)
    });
```

**Comment by JonJagger** [comment]
Hi Diego,
the screenshot of the proposed new kata/edit/ID entrance dialog is what I was thinking yes.
Now I see it I agree the grouping you have make sense.
In fact, I think it makes sense to change the wording/focus a little...
I propose that the wording becomes

 The id of _your_ exercise is
 ....

Then have a title "version-control" (instead of traffic-lights)
Then have text (in a single grey box) that reads...
"is built into cyber-dojo. Each test run creates a new traffic-light:
...."

Excellent!
Thanks

**Comment by JonJagger** [comment]
```
const $editKata = (kataId) => {
      const $reenterButton = $('a.button.reenter');
      $reenterButton.attr('href', `/kata/edit/${kataId}`).attr('target', "_blank");
      $reenterButton[0].click();
    }
    $div.click(() => {
        $editKata(kataId)
    });
```

For me this does not reveal its intention as well as it might.
I see a method called $editKata and yet when I call it, it does not edit a kata.
What is does is take me to a new page whose URL is /kata/edit.
So maybe the name $openKataInNewWindow ? or $openKataInNewTab ?

And you are right about the [0]
I'd missed that. Good one :-)

**Comment by JonJagger** [comment]
Also, instead of
```
$div.click(() => {
        $editKata(kataId)
    });
```
I think you can just do this
```
$div.click(() => $editKata(kataId));
```

**Comment by diegopego** [comment]
> Hi Diego,
> the screenshot of the proposed new kata/edit/ID entrance dialog is what I was thinking yes.
> Now I see it I agree the grouping you have make sense.
> In fact, I think it makes sense to change the wording/focus a little...
> I propose that the wording becomes
> 
> The id of _your_ exercise is
> ....
> 
> Then have a title "version-control" (instead of traffic-lights)

Changing the title should impact on the name of the info button? https://github.com/diegopego/web/blob/de0e1c24858e1168bbfab4dbff7ed1deb2aebeb9/app/views/shared/_traffic_lights.html.erb#L1
I don't like breaking changes, but if the title is no longer traffic-lights, maybe the button should be changed to something like "version-control"?

> Then have text (in a single grey box) that reads...
> "is built into cyber-dojo. Each test run creates a new traffic-light:
> ...."
> 
> Excellent!
> Thanks

**Comment by diegopego** [comment]
This is how it would look like:
image

I increased the width from 500 to 600 (not sure if this is desirable) and tried different wording.
image

I wanted to use this phrase:
"Each test run creates a new commit with a traffic-light:"
But it would have a line break:
image

**Comment by JonJagger** [comment]
Excellent. I like this.
Maybe use wording "Each test run creates a new commit + traffic-light:"
That should probably fit.
You're right about the breaking changes.
I agree re changing the title of the button to "version-control".

**Comment by JonJagger** [comment]
Also, when would be a good day+time for you to do another pairing session?

**Comment by diegopego** [comment]
> Also, when would be a good day+time for you to do another pairing session?

Saturdays and Sundays are the best - at any time.
For the other days, 16:00 to 19:00 (London) or any time from 21:00 (London).
I can rearrange my schedule to fit yours.

**Comment by diegopego** [comment]
What do you think is best? Make the style consistent with the other info, or bring the green input box style?
image

**Comment by diegopego** [comment]
I liked this one better:
image

**Comment by diegopego** [comment]
I'm having problems with the phonetics and the box width. how big can we make it?
Most of the times, the line is wrapped, but sometime, this is what occures:

image

**Comment by JonJagger** [comment]
Hi Diego.
Re the box whose text reads:
"The ID of the exercise is:"

I'd prefer for this to be above the title "version control" since its not really about version-control.
I'd prefer the text to read "The ID of your exercise is:"
As for the width where the phonetics have variable width...
I like what you've done and suggest
- making the font for each each phonetic word slightly smaller
- increasing the width of the dialog a bit

I don't think we should worry if a rare id has lots characters with long phonetics (eg November)
which cause a line wrap. We can worry about that later if we want to.
If think its better instead that we get your work into production :-)

**Comment by diegopego** [comment]
> I'd prefer for this to be above the title "version control" since its not really about version-control.
Does this dialog need a title? Maybe a more comprehensive one like "Exercise info".
With this in mind, what about the name of the button that re-open this dialog?, maybe change it to "exercise info"?

image

image

**Comment by JonJagger** [comment]
Yes I like this. I was thinking the info about the ID could go above the title. But of course that's nonsense - it can't.
Let's recap. This is the dialog that appears when you first enter your session at /kata/edit/ID (and also if you refresh and do not yet have any traffic-lights). So I think it is important that this dialog shows both
- the ID (since that is not shown from creator anymore
- info about version-control

So I think
- let's make the title of the dialog be "version-control" to match the button name
- let's make the 1st grey-box under that a deeper one that combines 
  - (o) the grey-box starting "Version control is built in". 
  - (o)the grey-box starting "Click any traffic-light..."
  - (o) the grey-box starting "In a group practice..."
- then the 2nd grey-box starting "Tests must complete in..."
- then the 3rd grey-box starting "The ID of your exercise is..."

Lastly, instead of saying 
"Each test run creates a new commit + traffic-light:" 
lets just say
"Each test run creates a new traffic-light:" 

See you at 7:00 :-)

**Pull request closed without merging**
